### PR TITLE
Update to decode unicode strings

### PR DESCRIPTION
**Pull request by jatinn**
Sometimes a copy/paste is all you need :smile:

### CODE REVIEW

**Comment by oldmantaiter** [comment]
@jatinn Would this be something that would benefit the upstream repo as well?

**Comment by jatinn** [comment]
Yes

**Comment by oldmantaiter** [comment]
@jatinn Ok, might as well submit the PR upstream and get the author to merge up there so we can merge it back into ours. If the upstream author take s a while, we can always just merge it here and deal with any subsequent upstream merge.

**Comment by jatinn** [comment]
Ok sounds good I'll send a PR there as well.

**Comment by jatinn** [comment]
Since I created a fork from ours I see we also added functions to handle arrays, floats and bools. Do we want to send those to upstream as well (I think we should) or should I just submit the utf fix?

**Comment by oldmantaiter** [comment]
Yep, might as well do everything

**Comment by jatinn** [comment]
Ok sounds good

**Pull request merged**
